MDRIP/Models/Occurrence.cs
using MvcValidationExtensions.Attribute;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MDRIP.Models
{
	public class Occurrence
    {
        public int ID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
		[Display(Name = "Reported Location")]
		public string ReportedLocation { get; set; }
		public string District { get; set; }
        [Required]
        [Display(Name = "Start Date")]
        public DateTime StartDate { get; set; }
        [Required]
        [Display(Name = "End Date")]
		[GreaterThan("StartDate", ErrorMessage = "End date must be before the end date")]
		public DateTime EndDate { get; set; }
        public long Prevalence { get; set; }
		[Display(Name = "Death Rate")]
		public long DeathRate { get; set; }
        public Bacteria Bacteria { get; set; }
		public Infection Infection { get; set; }

		public string User_ID { get; set; }

        public ICollection<OccurrenceAttachment> Attachments { get; set; }

    }
}

MDRIP/Controllers/OccurrencesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MDRIP.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace MDRIP.Controllers
{
    [Authorize]
    public class OccurrencesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        #region UserManager
        private ApplicationUserManager _userManager;

        public OccurrencesController()
        {
        }
        public OccurrencesController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        #endregion

		// GET: Occurrences
		public ActionResult Index(string searchString)
        {
            var user = UserManager.FindById(User.Identity.GetUserId());

            var occurrence = db.Occurrences.Include(x=>x.Bacteria).Include(x => x.Infection).Include(x => x.Attachments);
            var occurrences = occurrence;
            if (!String.IsNullOrEmpty(searchString))
            {
                occurrences = occurrence.Where(s => s.ReportedLocation.ToLower().Contains(searchString.ToLower()));
                occurrences = occurrences.Union(occurrence.Where(s => s.District.ToLower().Contains(searchString.ToLower())));
                occurrences = occurrences.Union(occurrence.Where(s => s.Bacteria.Name != null && s.Bacteria.Name.ToLower().Contains(searchString.ToLower())));
                occurrences = occurrences.Union(occurrence.Where(s => s.Infection.Name != null && s.Infection.Name.ToLower().Contains(searchString.ToLower())));
                occurrences = occurrences.Union(occurrence.Where(s => s.Attachments.Count > 0 && s.Attachments.Any(x=> x.Name.ToLower().Contains(searchString.ToLower()))));
            }

            if (User.IsInRole("ResearcherScientist"))
            {
                return View(occurrences.Where(i => i.User_ID == user.Id).Include(i=>i.Bacteria).Include(i=> i.Infection).Include(i => i.Attachments).ToList());
            }
            else
            {
                return View(occurrences.Include(i => i.Bacteria).Include(i => i.Infection).Include(i=>i.Attachments).ToList());
            }
        }

        // GET: Occurrences/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Occurrence occurrence = db.Occurrences
                .Include(x=>x.Infection)
                .Include(x => x.Bacteria)
                .Include(x => x.Attachments)
                .Where(x=>x.ID == id).SingleOrDefault();

            if (occurrence == null)
            {
                return HttpNotFound();
            }
            
            return View(occurrence);
        }

        // GET: Occurrences/Create
        public ActionResult Create() {

            var bact = db.Bacteria.OrderBy(x=>x.Name).ToList();
            var inf = db.Infections.OrderBy(x => x.Name).ToList();
            var lst = new List<InfectionBacteria>();
            bact.ForEach(x => lst.Add(new InfectionBacteria() { ID = x.ID, Name = "Bacteria - " + x.Name, Type="Bacteria" }));
            inf.ForEach(x => lst.Add(new InfectionBacteria() { ID = x.ID, Name = "Infection - " + x.Name, Type = "Infection" }));

            var OccurencesViewModel = new OccurencesViewModel
            {
                Bacteria = db.Bacteria.ToList(),
                Infection = db.Infections.ToList(),
                InfsBacts = lst,
                Regions = db.Regions.Include(r => r.Country).OrderBy(r => r.Country.Name).ThenBy(r => r.Name).ToList()
			};
            return View(OccurencesViewModel);
        }

        // POST: Occurrences/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(OccurencesViewModel model)
        {


            //if (ModelState.IsValid)
            //{

                // Model validation
                if (string.IsNullOrWhiteSpace(model.InfectionBacteriaID) ||
                    string.IsNullOrWhiteSpace(model.Occurence.ReportedLocation) ||
                    string.IsNullOrWhiteSpace(model.Occurence.District) ||
                    model.Occurence.StartDate == null) {

                var bact = db.Bacteria.OrderBy(x => x.Name).ToList();
                var inf = db.Infections.OrderBy(x => x.Name).ToList();
                var lst = new List<InfectionBacteria>();
                bact.ForEach(x => lst.Add(new InfectionBacteria() { ID = x.ID, Name = "Bacteria - " + x.Name, Type = "Bacteria" }));
                inf.ForEach(x => lst.Add(new InfectionBacteria() { ID = x.ID, Name = "Infection - " + x.Name, Type = "Infection" }));

                var OccurencesViewModel = new OccurencesViewModel
                {
                    Bacteria = db.Bacteria.ToList(),
                    Infection = db.Infections.ToList(),
                    InfsBacts = lst,
                    Regions = db.Regions.Include(r => r.Country).OrderBy(r => r.Country.Name).ThenBy(r => r.Name).ToList(),
                    Occurence = model.Occurence,
                    InfectionBacteriaID = model.InfectionBacteriaID
                };
                return View(OccurencesViewModel);

            } else { 

                string infectionPrefix = "Infection - ";
                string bacteriaPrefix = "Bacteria - ";

                if (model.InfectionBacteriaID.Contains(infectionPrefix)) { // infection
                    model.InfectionID = Convert.ToInt32(model.InfectionBacteriaID.Substring(infectionPrefix.Length, model.InfectionBacteriaID.Length - infectionPrefix.Length));
                    model.Occurence.Infection = db.Infections.Where(u => u.ID == model.InfectionID).SingleOrDefault();
                }
                else
                {
                    model.BacteriaID = Convert.ToInt32(model.InfectionBacteriaID.Substring(bacteriaPrefix.Length, model.InfectionBacteriaID.Length - bacteriaPrefix.Length));
                    model.Occurence.Bacteria = db.Bacteria.Where(u => u.ID == model.BacteriaID).SingleOrDefault();
                }

                model.Occurence.User_ID = User.Identity.GetUserId();

                if (model.Occurence.ID > 0)
                {
                    db.Entry(model.Occurence).State = EntityState.Modified;
                }
                else
                {
                    db.Occurrences.Add(model.Occurence);
                }
                db.SaveChanges();

                SaveAttachments(model.Occurence);

                return RedirectToAction("Index");
            }    

        }

        private void SaveAttachments(Occurrence occurrence)
        {
            var subPath = "Attachments/Occurrences/" + occurrence.ID + "/";
            bool exists = Directory.Exists(Server.MapPath("~/" + subPath));
            if (!exists)
            {
                Directory.CreateDirectory(Server.MapPath("~/" + subPath));
            }
            for (var i = 0; i < Request.Files.Count; i++)
            {
                HttpPostedFileBase hpf = Request.Files[i];
                var fileName = Path.GetFileName(hpf.FileName);
                if (fileName == null || fileName == "")
                {
                    break;
                }

                var path = Path.Combine(subPath, fileName);
                hpf.SaveAs(Server.MapPath("~/" + path));
                OccurrenceAttachment a = new OccurrenceAttachment()
                {
                    Name = fileName,
                    Occurrence = occurrence,
                    Link = path
                };
                db.OccurrenceAttachments.Add(a);
                db.SaveChanges();
            }
        }

        // GET: Occurrences/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Occurrence occurrence = db.Occurrences
                .Include(x => x.Infection)
                .Include(x => x.Bacteria)
                .Include(x => x.Attachments)
                .Where(x => x.ID == id).SingleOrDefault();

            if (occurrence == null)
            {
                return HttpNotFound();
            }

            var bact = db.Bacteria.OrderBy(x => x.Name).ToList();
            var inf = db.Infections.OrderBy(x => x.Name).ToList();
            var lst = new List<InfectionBacteria>();
            bact.ForEach(x => lst.Add(new InfectionBacteria() { ID = x.ID, Name = "Bacteria - " + x.Name, Type = "Bacteria" }));
            inf.ForEach(x => lst.Add(new InfectionBacteria() { ID = x.ID, Name = "Infection - " + x.Name, Type = "Infection" }));

            string infectionBacteriaID = "";
            if (occurrence.Bacteria != null)
            {
                infectionBacteriaID = "Bacteria - " + occurrence.Bacteria.ID;
            }
            else {
                infectionBacteriaID = "Infection - " + occurrence.Infection.ID;
            }

            var OccurencesViewModel = new OccurencesViewModel
            {
                Bacteria = db.Bacteria.ToList(),
                Infection = db.Infections.ToList(),
                InfsBacts = lst,

MDRIP/Views/Occurrences/Create.cshtml
@model MDRIP.Models.OccurencesViewModel

@{
    ViewBag.Title = "Create";
    ViewBag.NavTitle = " - Report an Occurrence";
}

<div class="row">

    <div class="card card-signup create-occurrence-form" data-background-color="orange">
        <div class="card-header text-center">
            <h3 class="card-title title-up">Occurrence</h3>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "Occurrences", FormMethod.Post, new { enctype = "multipart/form-data", id = "occurrenceForm" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <div class="form-group">
                        <select class="form-control" data-val="true" data-val-number="The field ID must be a number." data-val-required="The ID field is required." id="InfectionBacteria_ID" name="InfectionBacteriaID">
                            <option value="">Select Infection/Bacteria</option>
                            @foreach (InfectionBacteria infectionBacteria in Model.InfsBacts)
                            {
                                <option value="@infectionBacteria.Type - @infectionBacteria.ID">@infectionBacteria.Name</option>
                            }
                        </select>

                        @*@Html.DropDownListFor(model => model.InfectionBacteria.ID, new SelectList(Model.InfsBacts, "ID", "Name"), "Select Infection/Bacteria", new { @class = "form-control" })*@
                        @Html.ValidationMessageFor(model => model.InfectionBacteria.ID, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <input type="text" id="txtautocomplete" placeholder="Address" class="form-control" />
                    </div>

                    @Html.HiddenFor(model => model.Occurence.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Occurence.Latitude, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Occurence.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.HiddenFor(model => model.Occurence.ReportedLocation, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Occurence.ReportedLocation, "", new { @class = "text-danger" })

                    <div class="form-group">
                        <select class="form-control" id="Occurence_District" name="Occurence.District">
                            <option value="">Select Region/District</option>
                            @foreach (var reg in Model.Regions)
                            {
                                <option value="@reg.Name">@reg.Country.Name - @reg.Name</option>
                            }
                        </select>

                        @Html.ValidationMessageFor(model => model.Occurence.District, "", new { @class = "text-danger" })
                    </div>
                    <div class="row">
                        <div class="form-group col-md-6">
                            Start Date:
                            <input class="form-control custom-date-control"
                                   data-val="true" data-val-date="The field StartDate must be a date."
                                   data-val-required="The StartDate field is required." id="StartDate"
                                   name="Occurence.StartDate" type="date" value="@DateTime.Now.Year-01-01" />
                            @Html.ValidationMessageFor(model => model.Occurence.StartDate, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group col-md-6">
                            End Date:
                            <input class="form-control custom-date-control"
                                   data-val="true"
                                   data-val-date="The field EndDate must be a date."
                                   data-datepicker-color="primary"
                                   data-val-required="The EndDate field is required."
                                   id="EndDate" name="Occurence.EndDate" type="date"
                                   value='@DateTime.Now.ToString("yyyy-MM-dd")'>
                            @Html.ValidationMessageFor(model => model.Occurence.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            Prevalence:
                            @Html.EditorFor(model => model.Occurence.Prevalence, new { htmlAttributes = new { @class = "form-control", @Value="0", @min=0 } })
                            @Html.ValidationMessageFor(model => model.Occurence.Prevalence, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group col-md-6">
                            Death Rate:
                            @Html.EditorFor(model => model.Occurence.DeathRate, new { htmlAttributes = new { @class = "form-control", @Value = "0", @min = 0 } })
                            @Html.ValidationMessageFor(model => model.Occurence.DeathRate, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="">
                        <input type="file" id="Occurence_Attachment" name="Occurence.Attachment" class="form-control" accept=".xls,.xlsx,.csv,.CSV,.png,.jpeg,.jpg,.gif,.doc,.docx,.pdf,.PDF" multiple />
                    </div>

                    <div class="form-group">
                        <div class="justify-content-center text-center col-md-10 max-width-100">
                            @Html.ActionLink("Back to List", "Index")
                            <input type="submit" value="Create" onclick="javascript:document.getElementById('occurrenceForm').submit()" class="create-occurrence-button btn btn-neutral btn-round btn-lg" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYm1VJVWSDiBt5t4oW7CuEbHrW4bVrCI4&libraries=places"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script>
<script src="@Url.Content("/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>

<script type="text/javascript">
    google.maps.event.addDomListener(window, 'load', initialize);
    function initialize() {
        var autocomplete = new google.maps.places.Autocomplete(document.getElementById('txtautocomplete'));
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
            var places = autocomplete.getPlace();
            $("#Occurence_ReportedLocation").val(places.formatted_address);
            // $("#Occurence_District").val(places.address_components[0]["long_name"]);
            $("#Occurence_Latitude").val(places.geometry.location.lat());
            $("#Occurence_Longitude").val(places.geometry.location.lng());
            $("#Occurence_District")[0].value = places.address_components[0]["long_name"];
        });
    }


</script>

MDRIP/Views/Occurrences/Delete.cshtml
@model MDRIP.Models.Occurrence

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Occurrence</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Latitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Longitude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prevalence)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prevalence)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeathRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeathRate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#tables').addClass("active");
    });
</script>

MDRIP/Views/Occurrences/Edit.cshtml
@model MDRIP.Models.OccurencesViewModel

@{
    ViewBag.Title = "Edit - Occurrence";
    ViewBag.NavTitle = " - Edit an Occurrence";
}


<div class="row">

    <div class="card card-signup create-occurrence-form" data-background-color="orange">
        <div class="card-header text-center">
            <h3 class="card-title title-up">Occurrence</h3>
        </div>
        <div class="card-body">
            @using (Html.BeginForm("Create", "Occurrences", FormMethod.Post, new { enctype = "multipart/form-data", id = "occurrenceForm" }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <div class="form-group">
                    <select class="form-control" data-val="true" data-val-number="The field ID must be a number." data-val-required="The ID field is required." id="InfectionBacteria_ID" name="InfectionBacteriaID">
                        <option value="">Select Infection/Bacteria</option>
                        @foreach (InfectionBacteria infectionBacteria in Model.InfsBacts)
                        {
                            var infbact = infectionBacteria.Type + " - " + infectionBacteria.ID;
                            if (Model.InfectionBacteriaID == infbact)
                            {
                                <option value="@infbact" selected>@infectionBacteria.Name</option>
                            }
                            else
                            {
                                <option value="@infbact">@infectionBacteria.Name</option>
                            }

                        }
                    </select>
                    @Html.ValidationMessageFor(model => model.InfectionBacteria.ID, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    <input type="text" id="txtautocomplete" placeholder="Address" class="form-control" value="@Model.Occurence.ReportedLocation" />
                </div>

                @Html.HiddenFor(model => model.Occurence.Latitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occurence.Latitude, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Occurence.Longitude, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.Occurence.ReportedLocation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Occurence.ReportedLocation, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.Occurence.ID, new { htmlAttributes = new { @class = "form-control" } })

                <div class="form-group">
                    <select class="form-control" id="Occurence_District" name="Occurence.District">
                        <option value="">Select Region/District</option>
                        @foreach (var reg in Model.Regions)
                        {
                            if (Model.Occurence.District == reg.Name)
                            {
                                <option value="@reg.Name" selected>@reg.Country.Name - @reg.Name</option>
                            }
                            else
                            {
                                <option value="@reg.Name">@reg.Country.Name - @reg.Name</option>
                            }
                        }
                    </select>

                    @Html.ValidationMessageFor(model => model.Occurence.District, "", new { @class = "text-danger" })
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        Start Date:
                        <input class="form-control custom-date-control"
                               data-val="true" data-val-date="The field StartDate must be a date."
                               data-val-required="The StartDate field is required." id="StartDate"
                               name="Occurence.StartDate" type="date" value='@Model.Occurence.StartDate.ToString("yyyy-MM-dd")' />
                        @Html.ValidationMessageFor(model => model.Occurence.StartDate, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6">
                        End Date:
                        @if (Model.Occurence.EndDate == null)
                        {
                            <input class="form-control custom-date-control"
                                   data-val="true"
                                   data-val-date="The field EndDate must be a date."
                                   data-datepicker-color="primary"
                                   data-val-required="The EndDate field is required."
                                   id="EndDate" name="Occurence.EndDate" type="date"
                                   value='@DateTime.Now.ToString("yyyy-MM-dd")} '>
                        }
                        else
                        {
                            <input class="form-control custom-date-control"
                                   data-val="true"
                                   data-val-date="The field EndDate must be a date."
                                   data-datepicker-color="primary"
                                   data-val-required="The EndDate field is required."
                                   id="EndDate" name="Occurence.EndDate" type="date"
                                   value='@Model.Occurence.EndDate.ToString("yyyy-MM-dd")'>
                        }
                        @Html.ValidationMessageFor(model => model.Occurence.EndDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row">
                    <div class="form-group col-md-6">
                        Prevalence:
                        @Html.EditorFor(model => model.Occurence.Prevalence, new { htmlAttributes = new { @class = "form-control", @Value = Model.Occurence.Prevalence, @min = 0 } })
                        @Html.ValidationMessageFor(model => model.Occurence.Prevalence, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group col-md-6">
                        Death Rate:
                        @Html.EditorFor(model => model.Occurence.DeathRate, new { htmlAttributes = new { @class = "form-control", @Value = Model.Occurence.DeathRate, @min = 0 } })
                        @Html.ValidationMessageFor(model => model.Occurence.DeathRate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="">
                    <input type="file" id="Occurence_Attachment" name="Occurence.Attachment" class="form-control" accept=".xls,.xlsx,.csv,.CSV,.png,.jpeg,.jpg,.gif,.doc,.docx,.pdf,.PDF" multiple />
                    @foreach (var i in Model.Occurence.Attachments)
                    {
                        <div class="col-md-10">
                            <a href="@Url.Action("DownloadFile", "Utils")?link=@i.Link&name=@i.Name" target="_blank">@i.Name</a>
                            &nbsp;
                            <a href="@Url.Action("DeleteAttachment", "OccurrenceAttachments")/@i.ID" class="deleteattachment"><i class="fa fa-trash"></i></a>
                        </div>
                    }
                </div>

                <div class="form-group">
                    <div class="justify-content-center text-center col-md-10 max-width-100">
                        @Html.ActionLink("Back to List", "Index")
                        <input type="submit" value="Save" onclick="javascript:document.getElementById('occurrenceForm').submit()" class="create-occurrence-button btn btn-neutral btn-round btn-lg" />
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBYm1VJVWSDiBt5t4oW7CuEbHrW4bVrCI4&libraries=places"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tables').addClass("active");


		var baseUrl = "@Request.Url.Scheme" + "://" + "@Request.Url.Authority" + "@Request.ApplicationPath.TrimEnd('/')";

		$.ajax({
            type: "GET",
            url: baseUrl+"/api/Occurences/Get/@Model.Occurence.ID",
            datatype: "json",
            success: function (data) {
                $("#txtautocomplete").val(data[0].ReportedLocation);
            }
        });
    });

    google.maps.event.addDomListener(window, 'load', initialize);
    function initialize() {
        var autocomplete = new google.maps.places.Autocomplete(document.getElementById('txtautocomplete'));
        google.maps.event.addListener(autocomplete, 'place_changed', function () {
            var places = autocomplete.getPlace();
            console.log(places);
            $("#Occurence_ReportedLocation").val(places.formatted_address);
                //$("#District").val(places.address_components[0]["long_name"]);
            $("#Occurence_Latitude").val(places.geometry.location.lat());
            $("#Occurence_Longitude").val(places.geometry.location.lng());
            $("#Occurence_District")[0].value = places.address_components[0]["long_name"];
        });
    }
</script>