MDRIP/Models/Country.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MDRIP.Models
{
    public class Country
    {

        public int ID { get; set; }

        [Required]
        public string Name { get; set; }

        public string Geojson { get; set; }

        public ICollection<Region> Regions { get; set; }

    }
}

MDRIP/Controllers/CountriesController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MDRIP.helper;
using MDRIP.Models;
using Newtonsoft.Json.Linq;

namespace MDRIP.Controllers
{
	[Authorize(Roles = "Admin")]
	public class CountriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Countries
        public ActionResult Index()
        {
            var list = db.Countries.ToList();
            list.Sort((x, y) =>
                    x.Name.CompareTo(y.Name));
            return View(list);
        }

        // GET: Countries/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
			Country country = db.Countries.Where(c => c.ID == id).Include(c => c.Regions).FirstOrDefault();
			country.Regions = country.Regions.OrderBy(r => r.Name).ToList();
			if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // GET: Countries/Create
        public ActionResult Create()
        {
            return View(new CountryViewModel() { Countries = Helper.GetCountries() });
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Country country)
        {
            if (ModelState.IsValid)
            {
                var subPath = "Assets/map";
                bool exists = System.IO.Directory.Exists(Server.MapPath("~/" + subPath));
                if (!exists)
                {
                    System.IO.Directory.CreateDirectory(Server.MapPath("~/" + subPath));
                }
                HttpPostedFileBase hpf = Request.Files[0];
                var fileName = country.Name.ToLower().Trim() + ".json";
                var path = System.IO.Path.Combine(subPath, fileName);
                var fullPath = Server.MapPath("~/" + path);
                hpf.SaveAs(fullPath);
                country.Geojson = fileName;
                db.Countries.Add(country);
                db.SaveChanges();
                ReadJson(fullPath, country);
                return RedirectToAction("Index");
            }

            return View(country);
        }

        public void ReadJson(string path, Country country) {

            var json = System.IO.File.ReadAllText(path);
            try
            {
                var jObject = JObject.Parse(json);

                if (jObject != null)
                {
                    JArray features = (JArray)jObject["features"];
                    for (var i = 0; i < features.Count; i++) {
                        var feature = features[i];
                        var properties = feature["properties"];
                        var district = properties["districts"].ToString();
                        db.Regions.Add(new Models.Region()
                        {
                            Name = district,
                            Country = country
                        });
                    }
                    db.SaveChanges();
                }
            }
            catch (Exception e)
            {
            }
        }

        // GET: Countries/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Where(c=> c.ID == id).Include(c => c.Regions).FirstOrDefault();
            country.Regions = country.Regions.OrderBy(r=>r.Name).ToList();
            if (country == null)
            {
                return HttpNotFound();
            }
            
            return View(new CountryViewModel() { Countries = Helper.GetCountries(), Country = country });
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                var fileName = country.Name.ToLower().Trim() + ".json";
                country.Geojson = fileName;
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                try
                {
                    if (Request.Files.Count > 0)
                    {
                        db.Regions.RemoveRange(db.Regions.Include(r => r.Country).Where(r => r.Country.ID == country.ID));
                        db.SaveChanges();

                        var subPath = "Assets/map";
                        bool exists = System.IO.Directory.Exists(Server.MapPath("~/" + subPath));
                        if (!exists)
                        {
                            System.IO.Directory.CreateDirectory(Server.MapPath("~/" + subPath));
                        }
                        HttpPostedFileBase hpf = Request.Files[0];
                        var path = System.IO.Path.Combine(subPath, fileName);
                        var fullPath = Server.MapPath("~/" + path);
                        hpf.SaveAs(fullPath);
                        ReadJson(fullPath, country);
                    }
                }
                catch (Exception e) {
                    throw e;
                    //
                }

                return RedirectToAction("Index");
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Country country = db.Countries.Where(c => c.ID == id).Include(c => c.Regions).FirstOrDefault();
            country.Regions = country.Regions.OrderBy(r => r.Name).ToList(); if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Country country = db.Countries.Include(r=>r.Regions).Where(c=>c.ID == id).First();
            var path = Request.MapPath("~/Assets/map/" +country.Geojson);
            if (System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }
            db.Countries.Remove(country);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

MDRIP/Views/Countries/Create.cshtml
@model MDRIP.Models.CountryViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Countries", FormMethod.Post, new { enctype = "multipart/form-data", id = "createCountryForm" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Country.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control text-box single-line input-validation-error" data-val="true" data-val-required="The Name field is required." id="Country_Name" name="Country.Name" type="text" value="" aria-describedby="Country_Name-error" aria-invalid="true">
                    <option value="">Select a country</option>
                    @foreach (var item in Model.Countries)
                    {
                        <option value="@item">@item</option>
                    }
                </select>
                @*@Html.EditorFor(model => model.Country.Name, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Country.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="">
            <label class="control-label col-md-2">GeoJson File</label>
            <div class="col-md-10">
                <input type="file" id="GeoJsonFile" name="GeoJson" class="form-control" accept=".json,.geojson,.geo.json,.JSON" />
                @Html.ValidationMessageFor(model => model.Country.Geojson, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#tables').addClass("active");
    });
</script>

MDRIP/Views/Countries/Delete.cshtml
@model MDRIP.Models.Country

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>GeoJson File</dt>
        <dd>
            <div>
                <label class="control-label col-md-2">GeoJson File</label>
                <div class="col-md-10">
                    <a target="_blank" href="@Url.Action("DownloadFile", "Utils")?link=Assets/maps&name=@Model.Geojson">@Model.Geojson</a>
                </div>
            </div>
        </dd>
        @if (Model.Regions.Count > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Regions)
            </dt>

            <dd>
                @foreach (var region in Model.Regions)
                {
                    <label>@region.Name </label>
                }

            </dd>
        }
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#tables').addClass("active");
    });
</script>

MDRIP/Views/Countries/Details.cshtml
@model MDRIP.Models.Country

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Country</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            GeoJson File:
        </dt>
        <dd>
            <div>
                <div class="col-md-10">
                    <a target="_blank" href="@Url.Action("DownloadFile", "Utils")?link=Assets/maps&name=@Model.Geojson">@Model.Geojson</a>
                </div>
            </div>
        </dd>
        @if (Model.Regions.Count > 0)
        {
            <dt>
                @Html.DisplayNameFor(model => model.Regions)
            </dt>

            <dd>
                @foreach (var region in Model.Regions)
                {
                    <label>@region.Name </label>
                }

            </dd>
        }
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#tables').addClass("active");
    });
</script>

MDRIP/Views/Countries/Edit.cshtml
@model MDRIP.Models.CountryViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Countries",
                FormMethod.Post,
                new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Country</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Country.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.Country.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select class="form-control text-box single-line input-validation-error" data-val="true" data-val-required="The Name field is required." id="Country_Name" name="Country.Name" type="text" value="" aria-describedby="Country_Name-error" aria-invalid="true">
                    <option value="">Select a country</option>
                    @foreach (var item in Model.Countries)
                    {
                        if (Model.Country.Name == item)
                        {
                            <option value="@item" selected>@item</option>
                        }
                        else
                        {
                            <option value="@item">@item</option>
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.Country.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <label class="control-label col-md-2">GeoJson File</label>
            <div class="col-md-10">
                <a target="_blank" href="@Url.Action("DownloadFile", "Utils")?link=Assets/maps&name=@Model.Country.Geojson">@Model.Country.Geojson</a>
            </div>
        </div>
        <div>
            <label class="control-label col-md-6">Replace Existing GeoJson File</label>
            <div class="col-md-10">
                <input type="file" id="GeoJsonFile" name="GeoJson" class="form-control" accept=".json,.geojson,.geo.json,.JSON" />
                @Html.ValidationMessageFor(model => model.Country.Geojson, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (Model.Country.Regions.Count > 0)
        {
            <div class="form-group">
                <dl>
                    <dt>
                        @Html.DisplayNameFor(model => model.Country.Regions)
                    </dt>
                    <dd>
                        @foreach (var region in Model.Country.Regions)
                        {
                            <div>
                                <label>@region.Name &nbsp; </label> <a href="@Url.Action("DeleteRegion", "Regions")?id=@region.ID" class="fa fa-trash deleteRegion"></a><br />
                            </div>
                        }
                    </dd>
                </dl>
            </div>
        }
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
        crossorigin="anonymous"></script>
<script>

    $(document).ready(function () {
        $('#tables').addClass("active");
        $('.deleteRegion').on('click', function (event) {
            event.preventDefault();
            var con = confirm("Do you want to delete this region?");

            var element = this;

            if (con) {

                $.ajax({
                    type: "POST",
                    url: this.href,
                    dataType: "text",
                    success: function (resultData) {
                        element.parentNode.parentNode.removeChild(element.parentNode);
                    }
                });
            }
        });
    });

</script>

MDRIP/Views/Countries/Index.cshtml
@model IEnumerable<MDRIP.Models.Country>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                GeoJson: <a target="_blank" href="@Url.Action("DownloadFile", "Utils")?link=Assets/map/@item.Geojson&name=@item.Geojson">@item.Geojson</a>
            </td>
            <td>
                <a href="@Url.Action("Create", "Regions")?id=@item.ID">Add Regions</a> |
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
        crossorigin="anonymous"></script>
<script>
    $(document).ready(function () {
        $('#tables').addClass("active");
    });
</script>